### ISSUE TITLE
Complex custom view - buttons

### ISSUE THREAD

**Issue by OzBob** [plainionist/Plainion.Prism#1]
The RI demo:
default window popup Inotificaiton buttons: all ok
default window viewmodel buttons: all ok
customconfirmation buttons: all ok
'complex custom view' Apply/ok/cancel buttons have no effect.
'view injection into windowcontent' cancel has 'nullreferenceexception exception'
'view injection into popupwindows action' buttson: response is not recorded.
view injection in to window content : response is not recorded
view injection in to popupwindowaction : response is not recorded

**Comment by plainionist** [comment]
The PRI demos different approaches with their pros and cons. Not all of those work intentionally. Pls read the provided explanation
